# Generated by Django 5.0 on 2024-01-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Librarian", "Librarian")],
                default="Librarian",
                max_length=255,
            ),
        ),
    ]
