# Generated by Django 5.0 on 2024-01-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_member"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="outstanding_debt",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
