# Generated by Django 5.0 on 2024-01-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_member_outstanding_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="county",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
